#!/bin/sh

# auto - Launcher.
# Copyright (C) 2017 RedStone Development Group.
# Written in sh because the user may not have Perl...to run RedStone....

PID=bin/redstone.pid
MODS="Class::Unload DBI"

if [ "$1" = "start" ] ; then
    if [ -e $PID ]; then
    	if [ "$2" = "force" ]; then  
    	    echo "Starting RedStone. . ."
    	    bin/auto
    	    sleep 2
    	    if [ ! -r $PID ]; then
    	    	echo "Possible failed startup... check RedStone logs for more information."
    	    fi
        else
            echo "RedStone appears to be running already. Run ./auto start force to start anyway."
        fi
    else
    	echo "Starting RedStone. . ."
    	bin/auto
    	sleep 2
    	if [ ! -r $PID ]; then
    		echo "Possible failed startup... check RedStone logs for more information"
    	fi
    fi

elif [ "$1" = "stop" ]; then
    echo "Stopping RedStone. . ."
    kill -TERM `cat $PID`

elif [ "$1" = "rehash" ]; then
    echo "Rehashing RedStone. . ."
    kill -HUP `cat $PID`

elif [ "$1" = "status" ]; then
    if [ -e $PID ]; then
    	echo "Status: RedStone appears to be running."
    else
    	echo "Status: RedStone appears to not be running."
    fi

elif [ "$1" = "getmodules" ]; then
    cpan -i $MODS

else
    echo "Usage: auto (start|stop|rehash|status|getmodules)"
fi

# vim: set ai et sw=4 ts=4:
